language: node_js
node_js: 14
branches:
  only: master
cache:
  npm: false
  directories:
    - '.yarn/cache'
deploy:
  fqdn: quisido.com
  keep-history: true
  local-dir: build
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
  github-token:
    secure: m1udmAf6k/wLTCHNrZ+7SfN0n1tO4UBIk3YVpW9dI7NunyVhs1IcymxSDVnskrxf80zIGygfMOfFBticiDkLIN9VkFjK/ltcyhF58R5CzLpWRtL59mfbEXuABvVQ3gwgHHvHFXQHapl7QVh9piieyoMfYzXzzONTQrYM2MVmUuyr0pLKu9wAbA1kqubfSUo8TvLqCefEYiAXCHYgnQ6N3mJ6N8gSW1MwGKObp0GTnAbABaN8Tjx2Zw8GjbtBebhNbsgxTEir2ZiScPeUqhzhDnmcyF296FRNVLmtcS5RH10G7Rwgt4cIGwHkEDdmwEqHpegl24ZCEFy9bU1PSdPABuHWqwgL6sl0v7Ba6xUnvL1+jR3vFES4BSS8E8tbaVWqgw3qJk35EGBraQpjPXKwt/NH6mlosBbE3YYi8lIpkADGpD9rqmrrkgIkJKglqJRPOCoAe8vWA0+H1/nK9ojUdeZm47I8UkTyjZL1squchq5gqJ/iY+sCFAQv78RrtkwF9Uy2SJVnZMonP+yyLLj0uSBD66GULO5Xi9Sq/g4oOJxN+AHTle4HFwSK3IH3hWONuTTVSlmqvC3LDMzOCltpr4Wdz9+ikb2mm9tcjHfrobpuIDXcUckTr2SRVYTjTAUueiD5IVekjnqFZv7qdhUZ6WqZtxMtHTchJ+aw4oZLBFM=
  on:
    branch: master
install:
  - yarn
script:
  - yarn test
  - yarn build
