language: node_js
node_js: 8.9.1
branches:
  only: master
cache: yarn
install: yarn
script:
- yarn build
deploy:
  fqdn: quisido.com
  github-token:
    secure: pniqht7axSIufpwVELq2RaOXhemMrxr/Gh4nCiPNlKwuHvg/SFrG5CyL7AVOodNAwkrrsMLRCLLDmjz+OMXyZTL13INrnJ1GEkDaTkkyBvdjTwI5FpVD5DsYUG8ukcynMiukxYPYMjQyoOM4uf3xwoJqE+nM8CU6DbiWEPfSHSwfmdrRx6VPNac6HmEBIUa1N3RPyeiY6TECC8j6fblAj2Bn1Uvons9y4yvNQ0Vt31Q61Q5hp6e8xWrDIJvLwWUa0fE1tPGBpSVe4V1wqhOaE4UFsMI287kFP3kiZWnWcwnqs5oVWral8KysdDFZPEUGw/GgR4GODY9epcezE1iAsFNA+pNopMwL92JsYVoW86I1NigL0sUmV+CMktQKqfwSYEKuRMhhQLsCKbOn+ycB+p74ijdrQcAAQzQ2DLNG+yyOuNjqfk5XAb2FGefebRdop+4sLJpVDgP74PtWO16aDk0/DHsV91ed/AP5nD+ViaSh8sB9/csXvnG2gdNPoOP8+5Y4wDoWqNvBm83ScGWr191phBS+wn8JmqJ4sF6s+tY0TS5YS1U5wZ8qay+eKkH0PHYX33bZEMuTXd63xnSvq2Nvu2WWr7G5qwy1rzWNQIqvmPt0nZNtAzp5Qy5+KtYM2uZIFAodyjE9oxxc0UknhIpDrjADctTZ5ujs35tbUUI=
  keep-history: true
  local-dir: build
  on:
    branch: master
  provider: pages
  skip-cleanup: true
  target-branch: gh-pages
